/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package handin2;

import handin2.ControllerPart.Controller;
import handin2.ControllerPart.MainSceneController;
import handin2.ModelPart.Model;
import handin2.ModelPart.TernarySearchTree.TreeTest;
import handin2.ViewPart.View;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        //String filename = "data/denmark.osm.zip.obj";
         String filename = "/Users/saynab/Desktop/BFST23Group14/map/app/data/small.osm";
        var model = Model.load(filename);
        var view = new View(model, primaryStage);
        new MainSceneController(view.mainScene, model, view);
        new Controller(model, view);
        var TreeTest = new TreeTest();
        TreeTest.test1();
    }
}
